[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3 --flash-size 16mb --partition-table partitions/motif.csv"

[env]
ESP_LOG="warn"
ESP_HAL_CONFIG_PSRAM_MODE="octal"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
